### ISSUE TITLE
having issues with connecting

### ISSUE THREAD

**Issue by UNSPOKEN-GT** [kaisei-kto/script-ware-w#1]
Keeps spamming

'**[CONNECTION] Client disconnected.
[CONNECTION] Client connected.**'

No idea why, but if u got any fixes I could
try, I'd appreciate it.

**Comment by kaisei-kto** [comment]
Hello! I've tested it between Script-Ware and Krnl, it seems to be an issue on Script-Ware!

Feel free to report this to them;
Connecting to a websocket server once, triggers the open and close event intervally.

**Comment by UNSPOKEN-GT** [comment]
Alright, thanks for your time.
