### ISSUE TITLE
Isnt working

### ISSUE THREAD

**Issue by LockheedMartinos** [kaisei-kto/script-ware-w#2]
I dont know why that isnt working. Some help please 

Discord : 𝓛𝓸𝓬𝓴𝓱𝓮𝓮𝓭#2734

**Comment by kaisei-kto** [comment]
What would the issue be? I will need some information such as... the game freezing, script causing errors or crashes.

**Comment by LockheedMartinos** [comment]
can you add me on discord? i will show you

**Comment by LockheedMartinos** [comment]
its telling me : " [EXECUTION] Failed! No clients are connected!"
